version: '3'

services:

  app:
    container_name: avito_test_task_app
    build: .
    ports:
      - 8080:8080
    volumes:
      - api:/go/scr/app/
    depends_on:
      - db
    networks:
      - test_task
    restart: on-failure
    links:
      - db

  db:
    image: postgres:latest
    container_name: avtio_test_task_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_SSLMODE=${DB_SSLMODE}
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    networks:
      - test_task

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - test_task
    restart: unless-stopped

volumes:
  api:
  db_data:

networks:
  test_task:
    driver: bridge
